---
# vars file for mq-testing
MQM_BIN_PATH: "/opt/mqm/bin"
queuemgrs: 
  - name: "AVSDEVCAL"
    queue: 
      - "AVSDEVCAL1.LOCAL.QUEUE"
      - "AVSDEVCAL2.LOCAL.QUEUE"
    channel: "AVSDEVCAL.SRVCONN"
    listener: "AVSDEVCAL.LISTENER"
    is_dr: false
    is_ha: true
    size: "1024M"
    listen_port: "1501"
enable_rdqm: true
create_queues: false

mqm_uid: 1001
mqm_gid: 1001

version: 9.3.2
os: rhel 
rel: el8

mq_storage_dev: vdb
rdqm_storage_dev: vdc

# Some env vars here

MQ_INSTALLATION_PATH: /opt/mqm
